apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - helmrelease.yaml

configMapGenerator:
  - name: cilium-static-values
    namespace: kube-system
    files:
      - values.yaml=values.yaml # Looks for values.yaml in the SAME folder
    options:
      disableNameSuffixHash: true
