{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rustfs.fullname" . }}
  labels:
    {{- include "rustfs.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- if .Values.ingress.s3.enabled }}
    - host: {{ .Values.ingress.s3.host | quote }}
      http:
        paths:
          {{- range .Values.ingress.s3.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "rustfs.fullname" $ }}-svc
                port:
                  name: {{ $.Values.ingress.s3.servicePort }}
          {{- end }}
    {{- end }}
    {{- if .Values.ingress.console.enabled }}
    - host: {{ .Values.ingress.console.host | quote }}
      http:
        paths:
          {{- range .Values.ingress.console.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "rustfs.fullname" $ }}-svc
                port:
                  name: {{ $.Values.ingress.console.servicePort }}
          {{- end }}
    {{- end }}
{{- end }}