kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: local
nodes:
  - role: control-plane
    # 1. Map Host ports to specific NodePorts
    # This bridges: Laptop Port 80/443 -> Kind Container Port 30080/30443
    # This allows you to access https://localhost
    extraPortMappings:
      - containerPort: 30080
        hostPort: 80
        protocol: TCP
      - containerPort: 30443
        hostPort: 443
        protocol: TCP
    # 2. (Optional) Persist data for Sail/Spark if needed
    # extraMounts:
    #   - hostPath: /tmp/sail
    #     containerPath: /tmp/sail

  - role: worker
  - role: worker
  - role: worker

networking:
  # 3. Critical for Cilium Installation
  disableDefaultCNI: true

  # # 4. Critical for 'kubeProxyReplacement=true'
  # # We tell Kind NOT to install kube-proxy, so Cilium can fully take over
  # # using eBPF for maximum performance and Zero Trust visibility.
  kubeProxyMode: "none"

  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
