[project]
name = "cdk8s-cli"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "cdk8s-plus-33>=2.4.3",
    "constructs~=10.4.3",
    "pulumi-ovh>=2.9.0",
]

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
