apiVersion: v1
kind: Service
metadata:
  name: {{ include "garage-webui.fullname" . }}
  labels:
    {{- include "garage-webui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ include "garage-webui.fullname" $ }}
  selector:
    {{- include "garage-webui.selectorLabels" . | nindent 4 }}
