apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources.yaml
  - cilium.yaml
  - cert-manager.yaml
  - cluster-config.yaml

# This takes your local file and turns it into the ConfigMap used above
configMapGenerator:
  - name: cilium-static-values
    files:
      - values.yaml=cilium-values.yaml # key=filename
