apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources.yaml
  - cilium.yaml
  - cert-manager.yaml
  - cluster-config.yaml

configMapGenerator:
  - name: cilium-static-values
    namespace: kube-system
    files:
      - values.yaml=../values/cilium-values.yaml
    # ADD THIS BLOCK:
    options:
      disableNameSuffixHash: true
