apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources.yaml
  - cilium.yaml
  - cert-manager.yaml
  - cluster-config.yaml

configMapGenerator:
  - name: cilium-static-values
    # FIX: Force this into the correct namespace
    namespace: kube-system
    files:
      - values.yaml=cilium-values.yaml
