# rustfs/Chart.yaml
apiVersion: v2
name: rustfs
description: A Helm chart for RustFS S3-compatible object storage (SNSD mode)
type: application
version: 0.1.0
appVersion: "latest"
icon: https://avatars.githubusercontent.com/u/151849438?v=4
