apiVersion: apps/v1
kind: Deployment
metadata:
  name: sail-spark-server
  namespace: {{ .Release.Namespace }} # Use Helm's release namespace
  labels:
    app.kubernetes.io/name: sail
    app.kubernetes.io/component: spark-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: sail
      app.kubernetes.io/component: spark-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sail
        app.kubernetes.io/component: spark-server
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- if and .Values.hostPaths.enabled .Values.hostPaths.paths }}
      volumes:
        {{- range .Values.hostPaths.paths }}
        - name: {{ .name }}
          hostPath:
            path: {{ .hostPath }}
            type: DirectoryOrCreate
        {{- end }}
      {{- end }}
      containers:
        - name: server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "sail" ]
          args: [ "spark", "server", "--ip", "0.0.0.0", "--port", "{{ .Values.service.targetPort }}" ]
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          {{- if and .Values.hostPaths.enabled .Values.hostPaths.paths }}
          volumeMounts:
            {{- range .Values.hostPaths.paths }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
          {{- end }}
          env:
            - name: RUST_LOG
              value: {{ .Values.config.rustLog | quote }}
            - name: SAIL_MODE
              value: {{ .Values.config.mode | quote }}
            - name: SAIL_CLUSTER__DRIVER_LISTEN_HOST
              value: "0.0.0.0"
            - name: SAIL_CLUSTER__DRIVER_EXTERNAL_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SAIL_KUBERNETES__IMAGE
              value: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            - name: SAIL_KUBERNETES__NAMESPACE
              value: {{ .Release.Namespace }}
            - name: SAIL_KUBERNETES__DRIVER_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SAIL_KUBERNETES__WORKER_SERVICE_ACCOUNT_NAME
              value: {{ .Values.serviceAccount.name }}
            {{- if .Values.hostPaths.enabled }}
            # This value is built by the helper template
            - name: SAIL_KUBERNETES__WORKER_POD_TEMPLATE
              value: {{ include "sail.workerPodTemplateDict" . | quote }}
            {{- end }}