apiVersion: v1
kind: Service
metadata:
  name: {{ include "sail-spark.fullname" . }}
  labels:
    {{- include "sail-spark.labels" . | nindent 4 }}
spec:
  type: {{ .Values.driver.service.type }}
  ports:
    - port: {{ .Values.driver.service.port }}
      targetPort: {{ .Values.driver.service.port }}
      protocol: TCP
      name: grpc
  selector:
    {{- include "sail-spark.selectorLabels" . | nindent 4 }}