apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # -------------------------------------------------------------
  # Gateway API (Experimental Channel)
  # -------------------------------------------------------------
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.0/experimental-install.yaml
