apiVersion: kustomize.config.k8s.io/v5
resources:
  # Update paths to point to 'base/'
  - base/sources.yaml
  - base/cilium.yaml
  - base/cert-manager.yaml
  - base/cluster-config.yaml

configMapGenerator:
  - name: cilium-static-values
    namespace: kube-system
    files:
      # Now this path is valid because 'values/' is a child directory
      - values.yaml=values/cilium.yaml
    options:
      disableNameSuffixHash: true
