apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repository.yaml
  - cilium/helmrelease.yaml
  - cert-manager/helmrelease.yaml
  - cluster-config/helmrelease.yaml

configMapGenerator:
  - name: cilium-static-values
    namespace: kube-system
    files:
      # FIX: Point to the file inside the 'cilium' directory
      - values.yaml=cilium/values.yaml
    options:
      disableNameSuffixHash: true
