apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "sail-spark.fullname" . }}
  labels:
    {{- include "sail-spark.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sail-spark.fullname" . }}
  labels:
    {{- include "sail-spark.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "sail-spark.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "sail-spark.fullname" . }}
  apiGroup: rbac.authorization.k8s.io