{{- if .Values.gateway -}}
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: {{ include "sail-spark.fullname" . }}-grpc-route
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}

  hostnames:
    - {{ .Values.gateway.host | quote }}

  rules:
    # Match ALL gRPC services/methods for this hostname
    - matches:
        - {} # Empty match means "Match Everything"
      backendRefs:
        - name: {{ include "sail-spark.fullname" . }}
          port: {{ .Values.driver.service.port }}
{{- end -}}